# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Standalone Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore './Client/SeongOn2eHomePage.Client.csproj'
      
    # Client project Build
    - name: Build Client project
      run: dotnet publish './Client/SeongOn2eHomePage.Client.csproj' -c Release -o build
      
    # GitHub Pages 배포
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build/wwwroot
        force_orphan: true
        keep_files: false
        allow_empty_commit: true

    - name: Clean up build artifacts
      if: always()
      run: rm -rf build
